### ISSUE TITLE
This is like the underside of.net core microservices

### ISSUE THREAD

**Issue by Anberm** [davidfowl/BedrockFramework#11]
It seems that there is no such thing as a pure.net microservices wheel in.net core, and it is desirable to have such a high-performance.net core microservices architecture in the direction of the future

**Comment by davidfowl** [comment]
@Anberm can you elaborate? How do you think this relates? It's basically a low level communication framework

**Comment by Anberm** [comment]
> @Anberm can you elaborate? How do you think this relates? It's basically a low level communication framework
Yes, it's basically a low level communication framework, but it's very broad to imagine.From there, expand into a microservices engine that supports multiple protocols [HTTP/HTTPS, TCP, WS, GRPC, MQTT...], each service is a high degree of autonomy, independent development and deployment, registration by the service discovery to Consul/Zookeeper, don't need to configure the provider address, modular RPC request pipeline, external gateway through a restful API request [Kestrel], internal asynchronous RPC calls, to join the mechanism of load balancing and fault tolerance, distributed cache middleware, and so on.It can also use k8s for service choreography.I wish there were official guidance

**Comment by tthiery** [comment]
RabbitMQ and other queuing frameworks are a big missing feature set in .NET Core. ASP.NET Core can be used with HTTP out of the box to start implementing. With queuing systems you have core communication libraries but the whole stack above (Middleware/Controller/Actions/routing...) is a DIY experience. In my experience services are mostly either HTTP or MQ driven. 

At least I am in the hope that the bedrock/Houdini stuff moves a bit into this area.

**Comment by Anberm** [comment]
[Micronetes](https://github.com/davidfowl/Micronetes) I think what I want is getting better
