### ISSUE TITLE
New protocol APIs proposal

### ISSUE THREAD

**Issue by thenameless314159** [davidfowl/BedrockFramework#114]
Hello, first of all thank you very much for this library, I learned a lot reading the wonderful code that it contains.

I have a proposal to make for a new protocol abstraction that is currently published on [this repository](https://github.com/thenameless314159/Andromeda.Network). I believe it can make implementation of any kind of length prefixed protocol less painful and easier in a different way than with the `IMessageReader` and `IMessageWriter` protocol abstractions of @davidfowl.

The logic is contained within the Andromeda.Framing library which provide read/write mechanism to handle any kind of length prefixed protocol.

Both mechanism works around the [`Frame` and `Frame<TMetadata>`](https://github.com/thenameless314159/Andromeda.Network/blob/master/src/Andromeda.Framing/Frame.cs) readonly structs. Here is a less verbose version of the frames (without docs) :

```csharp
public readonly struct Frame
{
    public static readonly Frame Empty = new(ReadOnlySequence<byte>.Empty, default!);

    public Frame(ReadOnlyMemory<byte> payload, IFrameMetadata metadata) =>
        (Payload, Metadata) = (new ReadOnlySequence<byte>(payload), metadata);

    public Frame(ReadOnlySequence<byte> payload, IFrameMetadata metadata) =>
        (Payload, Metadata) = (payload, metadata);

    public ReadOnlySequence<byte> Payload { get; }
    public IFrameMetadata Metadata { get; }

    public bool IsPayloadEmpty() =>  Metadata.Length == 0 && Payload.IsEmpty;
    public bool IsEmptyFrame() => Metadata == default! && Payload.IsEmpty;
}

public readonly struct Frame<TMetadata> where TMetadata : class, IFrameMetadata
{
    public static readonly Frame<TMetadata> Empty = new(ReadOnlySequence<byte>.Empty, default!);

    public Frame(ReadOnlyMemory<byte> payload, TMetadata metadata) =>
        (Payload, Metadata) = (new ReadOnlySequence<byte>(payload), metadata);

    public Frame(ReadOnlySequence<byte> payload, TMetadata metadata) =>
        (Payload, Metadata) = (payload, metadata);

    public ReadOnlySequence<byte> Payload { get; }
    public TMetadata Metadata { get; }

    public bool IsPayloadEmpty() => Metadata.Length == 0 && Payload.IsEmpty;
    public bool IsEmptyFrame() => Metadata == default! && Payload.IsEmpty;
}
```

## How it works

The library provides abstractions that must be implemented for a any kind of protocol such as [`IFrameMetadata`](https://github.com/thenameless314159/Andromeda.Network/blob/master/src/Andromeda.Framing/Metadata/IFrameMetadata.cs), [`IMetadataEncoder`](https://github.com/thenameless314159/Andromeda.Network/blob/master/src/Andromeda.Framing/Metadata/IMetadataEncoder.cs), [`IMetadataDecoder`](https://github.com/thenameless314159/Andromeda.Network/blob/master/src/Andromeda.Framing/Metadata/IMetadataDecoder.cs), and an [`IMetadataParser`](https://github.com/thenameless314159/Andromeda.Network/blob/master/src/Andromeda.Framing/Metadata/IMetadataParser.cs) which inherit from both two previous interfaces.

Here is the [`MetadataParser<TMetadata>`](https://github.com/thenameless314159/Andromeda.Network/blob/master/src/Andromeda.Framing/Metadata/MetadataParser.cs) base abstraction to implement :

```csharp
public abstract class MetadataParser<TMetadata> : IMetadataParser where TMetadata : class, IFrameMetadata
{
    public bool TryParse(ref SequenceReader<byte> input, out IFrameMetadata? metadata)
    {
        if (!TryParse(ref input, out TMetadata? meta))
        {
             metadata = default;
            return false;
        }

        metadata = meta;
        return true;
    }


    public void Write(ref Span<byte> span, IFrameMetadata metadata) => Write(ref span, (TMetadata)metadata);
    public int GetLength(IFrameMetadata metadata) => GetLength((TMetadata)metadata);
    public int GetMetadataLength(IFrameMetadata metadata) => GetLength(metadata);
        
    protected abstract bool TryParse(ref SequenceReader<byte> input, out TMetadata? metadata);
    protected abstract void Write(ref Span<byte> span, TMetadata metadata);
    protected abstract int GetLength(TMetadata metadata);
}
```

Once you've a protocol-specific implementation of an `IMetadataParser` you can use the main mechanism provided by the [`IFrameEncoder`](https://github.com/thenameless314159/Andromeda.Network/blob/master/src/Andromeda.Framing/IFrameEncoder.cs) and the [`IFrameDecoder`](https://github.com/thenameless314159/Andromeda.Network/blob/master/src/Andromeda.Framing/IFrameDecoder.cs) interfaces. 

The first mechanism is implemented by the [`PipeFrameEncoder`](https://github.com/thenameless314159/Andromeda.Network/blob/master/src/Andromeda.Framing/PipeFrameEncoder.cs) class which can be thread synchronizeded (or not) to write frames in a `PipeWriter` or `Stream`. A typed implementation also exists to handle typed `Frame<TMetadata>`.

The second one is implemented by the [`PipeFrameDecoder`](https://github.com/thenameless314159/Andromeda.Network/blob/master/src/Andromeda.Framing/PipeFrameDecoder.cs) class which provides methods to read single frames or consume them via an `IAsyncEnumerable<Frame>`. No thread synchronization is provided since read are mostly done with loops.  A typed implementation also exists to handle typed `Frame<TMetadata>`.

Here is a pseudo-code sample use using these APIs with untyped decoder/encoder :

```csharp
public class SomeProtocolHandler : ConnectionHandler
{
    public SomeProtocolHandler(IMetadataParser parser) => _someProtocolParser = parser;
    private readonly IMetadataParser _someProtocolParser;

    public async Task OnConnectedAsync(ConnectionContext connection)
    {
        await using var encoder = connection.Transport.Output.AsFrameEncoder(_someProtocolParser);
        await using var decoder = connection.Transport.Input.AsFrameDecoder(_someProtocolParser);
        
        try
        {
            await foreach(var frame in decoder.ReadFramesAsync(connection.ConnectionClosed))
            {
                var metadata = frame.Metadata as MyProtocolHeader ?? throw new InvalidOperationException("Invalid frame metadata !");
                var response = metadata.MessageId switch {
                    1 => encoder.WriteAsync(in someResponseFrame),
                    2 => encoder.WriteAsync(in anotherResponseFrame),
                    _ => throw new InvalidOperationException($"Message with Id={metadata.MessageId} is not handled !");
                }

                if(response.IsCompletedSuccessfully) continue;
                await response.ConfigureAwait(false);
            }
        }
        catch (ObjectDisposedException) { /* if the encoder throw this it means the connection closed, don't let this out */ }
    }
}
``` 
I unit tested and documented most of the code, all the tests can be found [on the repository](https://github.com/thenameless314159/Andromeda.Network/tree/master/tests/Andromeda.Framing.UnitTests).

Please let me know what you think of my protocols APIs I would really appreciate any kind of review. Of course i'm still learning so it might contains some bad code, and I didn't benched nor profiled the performance of the whole library so it's still a todo.

**Comment by thenameless314159** [comment]
I forgot to say, the purpose of this library is to reduce or remove completely the framing/serialization contained on protocol-specific message records/POCOs.

The best would be to use auto-generated serializer (via ET or the converter pattern used on the System.Text.Json, i've made a [serialization library](https://github.com/thenameless314159/Andromeda.Serialization) that provides this kind of stuff (not impletement currently)) to convert messages into payload.

This would make dispatching messages easier, let's say you have some kind of IFrameDispatcher with a decorator pattern to register the messages handlers like this : 

```csharp
public class FrameDispatcher : IFrameDispatcher, IFrameDispatcherBuilder
{
    public FrameDispatcher(IDeserializer deserializer, IMessageHandlerFactory factory) => 
        (_deserializer, _handlerFactory)  = (deserializer, factory);

    private delegate ValueTask Handler(Frame frame, IFrameEncoder encoder);
    private readonly Dictionary<int, Handler> _handlers = new();
    private readonly IMessageHandlerFactory _handlerFactory;
    private readonly IDeserializer _deserialize;

    public ValueTask OnFrameReceivedAsync(in Frame frame, ConnectionContext context) => 
        !_handlers.TryGetValue(frame.Metadata.MessageId, out var handler)
            ? // throw or do some handling to notify client message is not handled
            : handler(frame, context);

    public void Map<TMessage>(int withId) where TMessage : new()
    {
        _handlers[withId] = onFrame;

        async ValueTask onFrame(Frame frame, ConnectionContext context)
        {
            var payload = frame.Payload;
            var message = !payload.IsEmpty()
                ? _deserialize.Deserialize<TMessage>(ref payload)
                : new TMessage();

            // couldn't deserialize
            if(message is null) throw new InvalidDataException();

            var handler = _handlerFactory.Get();
            await foreach(var response in handler.OnMessageReceived(context.ConnectionClosed))
                await encoder.WriteAsync(in response).ConfigureAwait(false);
        }
    }
}
```

And for the message encoding you could make an extension of the PipeFrameEncoder that would take an ISerializer and expose a `ValueTask WriteMessageAsync<TMessage>(TMessage message, CancellationToken  = token)` method.

**Comment by shaggygi** [comment]
While I'm exited on the topic of having a better approach defining protocols, I was holding off on some work until it was better defined with Bedrock.  @thenameless314159 would this approach work to convert from objects > bytes (and vice-versa) if we had defined classes around something like Modbus?  See link for example https://ipc2u.com/articles/knowledge-base/detailed-description-of-the-modbus-tcp-protocol-with-command-examples/#desc.  If so, I can begin to really see the value of this (for client/server scenarios) and how it plugs into middleware pipelines.

**Comment by thenameless314159** [comment]
@shaggygi This approach is not about converting objects to payload, I made a [serialization library](https://github.com/thenameless314159/Andromeda.Serialization) for this purpose.
Here you only have frame metadata parsing logic, the payload to object convert logic is up to you, whether it's with an implementation of my library or with something else (json serialization, payload-less frames with metadata that provides infos to find the relevant message from a different channel...). I already answered all your questions on my previous comment so you may have to re-read them. I didn't looked your protocol spec in depth but it seems that it's a length prefixed protocol so my framing lib or the message reader/writer of @davidfowl would be a perfect match to implement it.

**Comment by davidfowl** [comment]
@thenameless314159 have you tried to migrate the protocols in here to use your new APIs (especially the text based protocols?)?

**Comment by thenameless314159** [comment]
No I haven't yet because the framing library was made to handle a specific game protocol at first. I might have been biased while writing it ? Because on my current projects using this library the goal was to respect the SRP principle and only have to define POCOs/records for the network messages without any serialization logic in them therefore it might not be well adapted to text based protocol if it's not length prefixed like with separators instead. (but I assume you wouldn't need a framing library if you have a text-base protocol with separator ? the PipeReader API should be fine enough ?)
But I can try to implement the rabbitmq protocol with it, should fit perfectly. What do you think ? Should I try to implement text based protocol and adapt the framing library to fit both ?

**Comment by thenameless314159** [comment]
I finally implemented some samples in the repository, a length-prefixed text-based protocol like your echo server but using the framing APIs, and an id prefixed binary-based protocol using the serialization and framing APIs. I also provided a second sample of the id prefixed protocol using the frame dispatcher mechanism I talked about, but with a simplified and straightforward implementation of it with no lookup/auto registration/method discovery logic atm (the aim would be to have something similar as your SignalR library with the lookup/descriptors and method discovery)
