### ISSUE TITLE
LengthPrefixedProtocol sample bug?

### ISSUE THREAD

**Issue by RayKoopa** [davidfowl/BedrockFramework#116]
Small issue, but shouldn't [this line](https://github.com/davidfowl/BedrockFramework/blob/8a965bbcba3a0a6f900d27f95c117ee3cd347967/samples/ServerApplication/LengthPrefixedProtocol.cs#L13)...
```cs
if (!reader.TryReadBigEndian(out int length) || input.Length < length)
```
... be ...
```cs
if (!reader.TryReadBigEndian(out int length) || input.Length - sizeof(int) < length)
```
...?

My understanding was:
- `input` includes all message bytes, including the 4-byte `length` prefix, and the variable length `payload`.
- The check is done to determine whether the variable number of `payload` bytes are available.
- Thus, the 4 bytes of `length` should be subtracted from `input.Length`.

**Comment by davidfowl** [comment]
Good catch! Do you want to send a pull request? You should actually be able to use [reader.Remaining](https://docs.microsoft.com/en-us/dotnet/api/system.buffers.sequencereader-1.remaining?view=net-5.0#System_Buffers_SequenceReader_1_Remaining).

**Comment by RayKoopa** [comment]
I did not know about `reader.Remaining`, good to know! I will submit a PR with it tomorrow.
