### ISSUE TITLE
NuGet doesn't work

### ISSUE THREAD

**Issue by adamradocz** [davidfowl/BedrockFramework#123]
It seems the NuGet feed doesn't work. I can't find the package, though I added the https://f.feedz.io/davidfowl/bedrockframework/nuget/index.json link to the `nuget.config` file.

**Comment by KieranDevvs** [comment]
I dont know if the nuget.config file is just for the CLI but if you want to get it to appear in VS you have to add it to the package sources in VS.

![image](https://user-images.githubusercontent.com/21192520/145679160-0acb34f6-1ff2-4634-a9a2-9b4d77ee526c.png)

![image](https://user-images.githubusercontent.com/21192520/145679166-a7183c2a-4d04-47d3-b4a8-c33836ac7a4a.png)

![image](https://user-images.githubusercontent.com/21192520/145679173-a4806812-8623-4f41-ab84-9c09d4b71003.png)

Hope that helps.

**Comment by adamradocz** [comment]
That's weird. Same settings and nothing...
Thanks anyway.

**Comment by TheDogg** [comment]
@adamradocz  make sure you check the box "Include Prerelease" and the packages should show up

**Comment by adamradocz** [comment]
Thanks, but I just realized the problem is, that I target .NET 6.
