### ISSUE TITLE
Out-of-Box BinarySerializer

### ISSUE THREAD

**Issue by shaggygi** [davidfowl/BedrockFramework#135]
Would be a nice-to-have serializer like the following for a standard approach on converting data to/from objects.

https://github.com/jefffhaynes/BinarySerializer

**Comment by KieranDevvs** [comment]
What's wrong with protobuf? It has good VS tooling support, requires near zero effort to setup and it's language agnostic too.
Just install the nuget package, write your proto schemas, and then VS will generate the stubs and message classes for you.

Usage is as simple as `MyType.Parser.ParseFrom(byte[]...);`, or `new MyType().ToByteArray();`

**Comment by shaggygi** [comment]
Thanks @KieranDevvs for the feedback and a good suggestion.  However, it would be nice to have more flexibility on the encoding/decoding on the various object properties of different types (int, double, float, etc.) based on the protocol being used.  For examples, BACnet doesn't have leading bytes in some scenarios for ints/uints.   There also might be cases where you have multiple bool properties that make up certain bits in a byte(s) to be processed. The `BinarySerializer` mentioned above appears to have attributes (have not done a deep dive yet) where you can add to the properties to perform the needed conversions and order to do so.

BTW, I don't want to downplay the BinarySerializer project as it might be a good solution.  Just was throwing this issue out to see if there was some related thinking/designing being added in Bedrock (or elsewhere within the core .NET libs) that would support (giving the warm/fuzzies a long-term solution 😄).

**Comment by davidfowl** [comment]
This project has no plans to implement a custom serializer. There are a bunch of good options including protobuf, message pack, [Hagar](https://github.com/ReubenBond/Hagar) etc

**Comment by shaggygi** [comment]
Understood, was mainly curious on thoughts.  Never heard of some of those mentioned I'll check out.  Thx

**Comment by jzabroski** [comment]
@shaggygi There is also Microsoft Bond, which supports 3 different formats for serialization, including 3 separate protocols:

* Simple Binary: No metadata. Basically impossible to decode without a schema. Schemas must match exactly to decode correctly.
* Compact Binary/Fast Binary: Has field types and field numbers, but no names. Can decode without a schema using a protocol reader/[transform](https://github.com/microsoft/bond/blob/master/examples/cpp/core/bf/main.cpp) directly. Backward/forward compatible changes handled without user intervention. See: https://microsoft.github.io/bond/manual/bond_cs.html <-- This is arguably the magic you want.
* JSON/XML: Has names but not exact field types. Backward/forward compatible changes handled without user intervention.

**Comment by shaggygi** [comment]
@jzabroski thank you for the info 👍
