### ISSUE TITLE
How can use WebSocket (help wanted)

### ISSUE THREAD

**Issue by sertunc** [davidfowl/BedrockFramework#137]
Hello, how can I use web socket protocol with wss schema in this framework? Thank you.

**Comment by KieranDevvs** [comment]
Unfortunately I don't think you can right now, the WebSocket protocol is in the experimental project and in my testing, it appears that there is some issue with how the header is sent in certain scenarios. https://github.com/davidfowl/BedrockFramework/issues/138

**Comment by sertunc** [comment]
I solved my problem using the following library

[Fleck](https://github.com/statianzo/Fleck)
