### ISSUE TITLE
Upgrade to .NET 7

### ISSUE THREAD

**Issue by TheVeryStarlk** [davidfowl/BedrockFramework#165]
BedrockFramework currently uses net6.0.

**Comment by ridomin** [comment]
.. and .NET8 is out as LTS

**Comment by adamradocz** [comment]
Unfortunately, this awesome project seems dead. :(

**Comment by smeddows** [comment]
> Unfortunately, this awesome project seems dead. :(

Adam, is this something that @davidfowl could confirm?

**Comment by davidfowl** [comment]
As dead as my free time 😄

**Comment by smeddows** [comment]
> As dead as my free time 😄

I hear that! LOL

I think this is exactly the type of general purpose constructs that I think really make a framework shine and get used a lot. With that being said, I would hate to see it go away.  I noticed there are a few milestones that you had documented in some of the other comments before you were ready for this to be "production ready".

Do you have any thoughts or quick ideas about how we could make this more community driver?  Is it as easy as forking it somewhere and then you pointing there for all the updates, etc.?

**Comment by adamradocz** [comment]
@davidfowl, out of curiosity. Is there any reason that you don't want to use this project inside ASP.NET Core? In that case the work and hobby would be the same :D

**Comment by davidfowl** [comment]
> @davidfowl, out of curiosity. Is there any reason that you don't want to use this project inside ASP.NET Core? In that case the work and hobby would be the same :D

The socket transport was lifted from kestrel.

Updated to .NET 8 and 9.
