### ISSUE TITLE
DuplexPipeStreamAdapter in a multithreaded context

### ISSUE THREAD

**Issue by jgiacobbi** [davidfowl/BedrockFramework#22]
Hello, I'm using bedrock in a multithreaded (worker) context. I have the write machinery guarded with a semaphor and have no issues writing regular traffic, but I consistently get a stack trace indicating that there is a write collision when a connection is closed. Is there a way to detect that this object is being disposed, or to synchronize with the CompleteAsync() call somehow? Is there something I'm not understanding about how to interact with the PipeWriter perhaps?

https://github.com/davidfowl/BedrockFramework/blob/master/src/Bedrock.Framework/Infrastructure/DuplexPipeStreamAdapter.cs#L40-L53

**Comment by davidfowl** [comment]
@jgiacobbi The PipeReader and PipeWriter aren't thread safe, you need locks/semaphores to overlap writes. See the [ProtocolWriter](https://github.com/davidfowl/BedrockFramework/blob/d310e05042e490eadda5352bebbe0966caacc74b/src/Bedrock.Framework/Protocols/ProtocolWriter.cs) as an example (this is a higher level API over the connection that writes a logical message).

Here's an example of using it (I highly recommend it):
https://github.com/davidfowl/BedrockFramework/blob/d310e05042e490eadda5352bebbe0966caacc74b/samples/ServerApplication/MyCustomProtocol.cs#L18-L47

**Comment by davidfowl** [comment]
If your stuck using the Stream then you still need to synchronize manually. Also never call Dispose while other code is running, it's unsafe.

**Comment by jgiacobbi** [comment]
All of my code is currently wrapped in a semaphor and is working correctly. The issue (as far as I can tell) is that the CompleteAsync() call in the adapter cannot be synchronized with from the same code.

**Comment by davidfowl** [comment]
> All of my code is currently wrapped in a semaphor and is working correctly. The issue (as far as I can tell) is that the CompleteAsync() call in the adapter cannot be synchronized with from the same code. I am also not calling DisposeAsync(). According to the stack trace it is being called from TlsServerConnectionMiddleware, presumably when the connection ends.

Can you explain more? Are you unwinding from the middleware when all of your operations are complete? Is your code still operating on the connection after the middleware unwinds?

**Comment by jgiacobbi** [comment]
I'm never intentionally unwinding the middleware, in the ideal case a client will remain connected 24/7 indefinitely.

The track trace indicates that the CompleteAsync() call triggers the "write pending" NotSupportedException, but it's never the other away around. Now that I type it out that seems strange because if it was a race I would expect to see my FlushAsync calls triggering it as well.

This is the stack trace:

```
The WriteAsync method cannot be called when another write operation is pending.
   at System.Net.Security.SslStream.WriteAsyncInternal[TWriteAdapter](TWriteAdapter writeAdapter, ReadOnlyMemory`1 buffer)
   at System.IO.Pipelines.StreamPipeWriter.FlushAsyncInternal(CancellationToken cancellationToken)
   at System.IO.Pipelines.StreamPipeWriter.CompleteAsync(Exception exception)
   at Bedrock.Framework.Infrastructure.DuplexPipeStreamAdapter`1.DisposeAsync()
   at Bedrock.Framework.Middleware.Tls.TlsServerConnectionMiddleware.InnerOnConnectionAsync(ConnectionContext context)
   at Bedrock.Framework.Middleware.Tls.TlsServerConnectionMiddleware.InnerOnConnectionAsync(ConnectionContext context)
   at Bedrock.Framework.Server.RunningListener.<>c__DisplayClass13_0.<<RunListenerAsync>g__ExecuteConnectionAsync|0>d.MoveNext()
```

**Comment by davidfowl** [comment]
> I'm never intentionally unwinding the middleware, in the ideal case a client will remain connected 24/7 indefinitely.

I believe you but it doesn't mean that isn't the cause. On the server side you own the loop and you own the code that is farming off the workers. Just make sure those are in sync before letting your logic unwind.

**Comment by jgiacobbi** [comment]
Sorry, that was a bad choice of words. I know clients are going to disconnect, the server isn't written as if bad things don't happen. There is a fixed number of workers, they receive messages as long as the BedrockConnectionHandler (implements `Microsoft.AspNetCore.Connections.ConnectionHandler`) is getting messages off the DuplexPipeStreamAdapter. When the connection ends, the OnConnectedAsync() method ends, and presumably then the using block [here](https://github.com/davidfowl/BedrockFramework/blob/master/src/Bedrock.Framework/Middleware/Tls/TlsServerConnectionMiddleware.cs#L203) attempts to dispose of the DuplexPipeStreamAdapter.

A writer class with a reference to the ConnectionContext writes replies as they are generated. It's possible that a message could be sent and the client could disconnect immediately, while the message is still being processed.

**Comment by davidfowl** [comment]
The writer class with the connection context can’t write after the middleware unwinds. That’s what you have to synchronize, don’t let the connection handler unwind until the work s drained for that connection context.

**Comment by jgiacobbi** [comment]
I see what you mean. In our scenario those delinquent replies are mostly never sent, but there is a small window before the server detects all handlers are gone. (a handful of stack traces in millions of messages).

I can wait for the semaphor to be open before returning control to Bedrock, hopefully that does the trick. Thanks for your patience.

**Comment by davidfowl** [comment]
Right, I’d recommend looking at the protocol writer. When you DisposeAsync , it’ll wait for any pending write to complete and then set a bool so they are no further writes possible past that point (assuming everything goes through the writer).
