### ISSUE TITLE
HttpRequestMessage requires Host header to be set

### ISSUE THREAD

**Issue by jkotalik** [davidfowl/BedrockFramework#24]
Http1RequestMessageWriter doesn't set the host header when it isn't set as a header. The host header is required, and in HttpClient, we add it directly if it isn't present: https://github.com/dotnet/runtime/blob/4f9ae42d861fcb4be2fcd5d3d55d5f227d30e723/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnection.cs#L256.

The URI for the host comes from the connection pool in HttpClient. We either require the host header to be set or pass it into the constructor of the Http1RequestMessageWriter.

**Comment by davidfowl** [comment]
PR?
