### ISSUE TITLE
Congestion Control 

### ISSUE THREAD

**Issue by bcronje** [davidfowl/BedrockFramework#27]
Is there an abstraction planned for different congestion control implementations for protocols? Or where does congestion control fit into the framework?

**Comment by davidfowl** [comment]
What sort of abstraction were you looking for? I'm not sure what a protocol agnostic congestion control looks like but would be very interested to learn more.

**Comment by bcronje** [comment]
I think it depends on the goals of this project. For the purposes of this discussion I'm specifically referring to network transport layer protocols like TCP/UDP and not higher layer protocols like HTTP.

I'm assuming implementing custom userspace TCP/UDP stacks falls outside the scope of this framework right?
That leaves us with transport protocols build on top of UDP like QUIC, which based on the project [description ](https://github.com/aspnet/AspNetCore/issues/4772) falls inside the scope. 

So the question is, do you realistically foresee any use-case for other UDP-based protocols apart from QUIC? If so, then there might be a case for a generic PacketTransportProtocol type base class that exposes the necessary hooks and signals for a protocol agnostic congestion control and other common aspects like loss detection etc.

If only QUIC support is planned, then I really hope the implementation planned for it includes support for pluggable congestion control and loss detection algorithms. 

Has any work started on the QUIC implementation yet, as I couldn't find anything in this repo yet?

**Comment by jkotalik** [comment]
> I'm assuming implementing custom userspace TCP/UDP stacks falls outside the scope of this framework right?

I'd think that is a good assumption. No matter what, you can abstract any way of getting a ConnectionContext via the [IConnectionListenerFactory](https://github.com/dotnet/aspnetcore/blob/master/src/Servers/Connections.Abstractions/src/IConnectionListenerFactory.cs) and IConnectionFactory interfaces, however our factory here abstracts TCP and UDP via System.Net.Socket: https://github.com/davidfowl/BedrockFramework/blob/master/src/Bedrock.Framework/Transports/Sockets/SocketConnection.cs. I'm not sure of the complete capabilities of System.Net.Socket, but we'd have to use Socket unless we wanted to re implement all of the TCP/UDP stack here.

> Has any work started on the QUIC implementation yet, as I couldn't find anything in this repo yet?

In Kestrel/dotnet runtime, we are adding QUIC support there. However, we will be invoking into a library that does QUIC on our behalf. Implementing QUIC is hard to say the least 😄

**Comment by jzabroski** [comment]
> In Kestrel/dotnet runtime, we are adding QUIC support there. However, we will be invoking into a library that does QUIC on our behalf. Implementing QUIC is hard to say the least 😄

What library is that?

**Comment by AlgorithmsAreCool** [comment]
@jzabroski 

MsQUIC
https://github.com/dotnet/aspnetcore/tree/master/src/Servers/Kestrel/Transport.MsQuic

**Comment by bcronje** [comment]
Thank you for the feedback.
