### ISSUE TITLE
Connection disconnected when input Chinese text

### ISSUE THREAD

**Issue by Ruikuan** [davidfowl/BedrockFramework#3]
Hi, David. Thanks for your wonderful framework for network transport!

I found an unexpected situation, using the demo client application, if I input English alphabets, it works very well, but if I input some Chinese text, such as `"我"` then press Enter, the connection will disconnect. 

Debugged into the code, found that if input Chinese, after the text transfer to server, in the server side, the `connection.Transport.Input` immediately become completed, so `CopyToAsync` break out.

Still investigating why.

**Comment by davidfowl** [comment]
Seems to work fine:

![image](https://user-images.githubusercontent.com/95136/65487917-c41b6d00-de5c-11e9-87de-189f35467096.png)

**Comment by Ruikuan** [comment]
I tested them in Powershell on Windows 10, maybe something wrong in this shell.

![image](https://user-images.githubusercontent.com/7594271/65488503-e1dbe700-dedb-11e9-813b-ed6fb6a2d415.png)

**Comment by Ruikuan** [comment]
The client application also work fine on my Debian9 WSL on the same Windows 10.
But it will disconnect in cmd/powershell, so maybe there is some issues in the conhost.

**Comment by Ruikuan** [comment]
For more info, I tried `Console.OpenStandardInput().CopyToAsync(File.Create("output.txt",1),1)`, it work as expected, all input Chinese text include lines was written to txt file.

I read the source code of `PipeWriter.CopyFromAsync` from [source.dot.net](https://source.dot.net/#System.IO.Pipelines/System/IO/Pipelines/PipeWriter.cs,114), seems the `IsCompleted` is not controlled by the source stream side.  Still don't understand...

**Comment by vicancy** [comment]
Is it because of the encoding/code page of your Powershell that the Chinese character is not Unicode encoded?

**Comment by davidfowl** [comment]
@Ruikuan it's been a while but let me know if it still reproduces. I don't think this has anything to do with the server or client implementation.
