### ISSUE TITLE
Provide support for factory method for building a derived instance of ConnectionHandler

### ISSUE THREAD

**Issue by robertmircea** [davidfowl/BedrockFramework#31]
I am using ServerBuilder `UseConnectionHandler` to build my Server class. I would like to resolve connection handler class from an external container (Castle Windsor) in order to be able to inject dependencies in my ConnectionHandler. I cannot find a way in the library' ServerBuilder API to resolve an instance of ConnectionHandler externally at client connect time

Is it feasible to use a factory method for resolving connection handlers?

**Comment by JanEggers** [comment]
the connectionhandler is resolved once per server not per connection.  then OnConnectedAsync is called per connection.

Im using the buildin DI and just added a ctor param and it worked fine.

**Comment by davidfowl** [comment]
The ServerBuilder takes an IServiceProvider, that’s your factory interface (albeit a very generic one). That’s what’s used to activate the connection handler

**Comment by robertmircea** [comment]
If ConnectionHandler is resolved only once per server (not per connection), it doesn't seem very useful. Usually you will want to resolve services at connection time. In this case, if I need to resolve a service at connection time, I would need to keep/request a reference to IServiceProvider which means that I will use Service Locator anti-pattern. 

For my usage, clearly a much better way would be to instantiate ConnectionHandler on each new client connection.

**Comment by davidfowl** [comment]
> For my usage, clearly a much better way would be to instantiate ConnectionHandler on each new client connection.

Make a new thing that isn't a connection handler and create that per connection.

> I would need to keep/request a reference to IServiceProvider which means that I will use Service Locator anti-pattern.

*Something* has to call GetService, it's call the composition root. It's only an anti-pattern when you do it outside of that place. In this case you have to do it because nothing else is activating you with the appropriate lifetime.

**Comment by robertmircea** [comment]
> The ServerBuilder takes an IServiceProvider, that’s your factory interface (albeit a very generic one). That’s what’s used to activate the connection handler. Wrap the container in your own implementation of that interface based on castle

I clearly understand this kind of api design, but why not give possibility to create the handler using a factory function similar to how HttpClient allows adding a http message handler. 

Something like this:
```
services.AddHttpClient("http")
.AddHttpMessageHandler(() => new PrometheusHandler(extraDependency));
```
or, alternatively (if the handler is registered in IServiceProvider):

```
services.AddHttpClient("http")
.AddHttpMessageHandler<PrometheusHandler>();
```

in our case would be:
```
            server = new ServerBuilder(serviceProvider)
                .UseSockets(sockets =>
                {
                    sockets.Listen(listeningEndpoint, builder => builder.UseConnectionHandler(()=> new MyCustomConnectionHandler(myDependencies) ));
                })
                .Build();
```

**Comment by JanEggers** [comment]
this is the original code:  https://github.com/aspnet/AspNetCore/blob/c17ce436b8703470231e7979cead042f5682c3f5/src/Servers/Connections.Abstractions/src/ConnectionBuilderExtensions.cs#L12-L18

you could add your own like:

```csharp
public static IConnectionBuilder UseConnectionHandler<TConnectionHandler>(this IConnectionBuilder connectionBuilder, Func<TConnectionHandler> factory) where TConnectionHandler : ConnectionHandler
        {
            var handler = factory():

            // This is a terminal middleware, so there's no need to use the 'next' parameter
            return connectionBuilder.Run(connection => handler.OnConnectedAsync(connection));
        }
```

I think this method does not provide enough value to be in the box.

**Comment by robertmircea** [comment]
> > For my usage, clearly a much better way would be to instantiate ConnectionHandler on each new client connection.
> 
> Make a new thing that isn't a connection handler and create that per connection.
> 

Just to make sure that I got it correctly. If I need to have dependencies injected in my `MySessionWithDependencyInjection` which is a transient service, I would need to do something like this? Is there any way/more elegant way to eliminate the direct serviceProvider call in my code?

```
    public class MyConnectionHandler : ConnectionHandler
    {
        private readonly IServiceProvider serviceProvider;

        public MyConnectionHandler(IServiceProvider serviceProvider)
        {
            this.serviceProvider = serviceProvider;
        }
        
        public override async Task OnConnectedAsync(ConnectionContext connection)
        {
            var session = serviceProvider.GetRequiredService<MySessionWithDependencyInjection>();
            session.Process(connection);
            [...]
        }
}
```

**Comment by JanEggers** [comment]
@robertmircea I think that is the smallest dependency you can depend on

you could use a func<MySessionWithDependencyInjection> and configure IServiceProvider to provide that but in the end that does not make a difference I think

**Comment by davidfowl** [comment]
@JanEggers what you suggested in cleaner.

```C#
public static IConnectionBuilder UseWhateverHandler <TConnectionHandler>(this IConnectionBuilder connectionBuilder, Func<TWhateverHandler > factory) where TWhateverHandler : WhateverHasNext
{
   return connectionBuilder.Run(connection => factory().Whatever(connection));
} 
```
