### ISSUE TITLE
Question: How can i pass some payload to ConnectAsync method from client to server.

### ISSUE THREAD

**Issue by mt89vein** [davidfowl/BedrockFramework#32]
Hi, i've started to learn this framework and built simple rabbitmq-like api. 
It would be great, if we can pass some payload to ConnectAsync method. Use case: add connection name, or some additional client provided properties for example application name etc. 
How can i achive this functionality ?

I've tried to add middleware to add connectionName into ConnectionContext.Items, but my middleware executes after actual connection to the server.

```csharp
services.AddTransient<IMqClient>(sp =>
{
    static Task Middleware(ConnectionContext connectionContext, Func<Task> next)
    {
        connectionContext.Items["connectionName"] = "test1";

        return next();
    }

    var cb = new ClientBuilder(sp);
    cb.Use(Middleware);

    var client = cb.UseSockets().Build();

    return new MqClient.MqClient(client);
});
```

Thanks.

**Comment by davidfowl** [comment]
Thanks for trying it out! This is one of the things missing from the existing interface. The best you can do right now is create a derived endpoint to pass extra data on it to connectasync. You can write a client side middleware like this https://github.com/davidfowl/BedrockFramework/blob/c383c4c0b7ed9243e379f06bd666b0db952744c8/samples/ClientApplication/DnsCachingConnectionFactory.cs#L12, that gets that endpoint and casts to something with more information.

**Comment by mt89vein** [comment]
Thanks :)
