### ISSUE TITLE
Implement websockets IMessageReader and IMessageWriter

### ISSUE THREAD

**Issue by davidfowl** [davidfowl/BedrockFramework#39]
The WebSocketMessageReader and WebSocketMessageWriter should support reading and writing raw websocket frames, we need to define the frame type of course and that's part of this design. I started porting the corefx implementation here (https://github.com/davidfowl/BedrockFramework/compare/davidfowl/websockets) which is still very incomplete.

- [x] - Define message types for reading and writing
- [x] - Implement WebSocketMessageReader
- [x] - Implement WebSocketMessageWriter
- [x] - Add tests, lots and lots of tests

**Comment by mattnischan** [comment]
Started taking a look at this tonight and started with a similar approach, looking at what corefx is doing, and also looking at my own implementation I wrote a while back that I had hooked into Kestrel back when WebSocket wasn't available (for Win7).

Is the idea here to make this relatively low level and return the payload as a sequence? Or, is this meant to be closer to Http*Message and wrap the content in a stream? I can see the plusses and minuses of both here, but it really is about who the intended consumer is, I suppose. Stream puts you into an allocation/copy path pretty much right away.

**Comment by mattnischan** [comment]
One more related question: in either the sequence or stream case, should the payload be de-masked, or is that at the consumer level? Again, pros and cons. I could certainly see the utility in de-masking on ReadAsync going the stream route.

**Comment by davidfowl** [comment]
Lower level API so thee API would return either a frame header that the user can use to parse the body (which might be a bit too painful as it requires unmasking), or we include the unmasked payload. I lean towards unmasking by default.

No automatic handling of pings/pongs though those get returned as frames. 

The idea behind this is to have an open stack that can be used to build more closed/opinionated clients/servers

**Comment by mattnischan** [comment]
I think, ultimately, the friendliest API I could think of would be to provide a message reader for the payload in the returned message itself. That message reader would provide an unmasked `ReadOnlySequence<byte>` from the input sequence and track the payload length.

Starting down that route there are some issues right away, though. It's not clear who should really own that memory. One thought I had is having the consumer provide a MemoryPool to allocate the unmasked data from, but there are a few issues with that. One is that the consumer now needs to properly return buffers and/or reset the sequence, and secondly (and related) I need an implementation of ReadOnlySequenceSegment<byte> that seems like it would be the same as Kestrel's BufferSegment. On it's face it seems somewhat like I'm implementing a PipeReader by the end of it? Which maybe that's actually the right idea here, not sure.

I'm probably missing something fundamental.

**Comment by davidfowl** [comment]
> I think, ultimately, the friendliest API I could think of would be to provide a message reader for the payload in the returned message itself. That message reader would provide an unmasked ReadOnlySequence<byte> from the input sequence and track the payload length.

Agreed!

> Starting down that route there are some issues right away, though. It's not clear who should really own that memory. One thought I had is having the consumer provide a MemoryPool to allocate the unmasked data from, but there are a few issues with that. One is that the consumer now needs to properly return buffers and/or reset the sequence, and secondly (and related) I need an implementation of ReadOnlySequenceSegment that seems like it would be the same as Kestrel's BufferSegment. On it's face it seems somewhat like I'm implementing a PipeReader by the end of it? Which maybe that's actually the right idea here, not sure.

Can't unmasking be done inplace? https://github.com/dotnet/runtime/blob/0ef0eb95e6de615320e7b0dba9646e80d0bc6049/src/libraries/Common/src/System/Net/WebSockets/ManagedWebSocket.cs#L1280

**Comment by mattnischan** [comment]
I think I was adhering to the "readonlyness" of ReadOnlySequence, but if that's a valid approach, that's exactly what I've done in my own implementations as well and should be easy enough to whip together.

**Comment by davidfowl** [comment]
> I think I was adhering to the "readonlyness" of ReadOnlySequence, but if that's a valid approach, that's exactly what I've done in my own implementations as well and should be easy enough to whip together.

No you're right, but we should absolutely violate the readonlyness where (don't quote me on that 😉 ).

**Comment by mattnischan** [comment]
Making some progress: https://github.com/davidfowl/BedrockFramework/compare/master...mattnischan:master

I have to think about the masking story on the send side a little bit, don't want an unobvious API situation where a frame is being multiplexed to multiple clients but the writer keeps masking the same buffer over and over (which would have the effect of it being alternating masked and unmasked).

**Comment by davidfowl** [comment]
The implementation looks really promising. I'm not a fan of the `WebSocketPayloadReader`, why not do it before returning? It should also be optimized for the single buffer vs multibuffer cases.

**Comment by mattnischan** [comment]
The WebSocket protocol allows a single frame to contain up to `ulong.MaxValue` (!) bytes in the payload. My assumption was that we would want the consumer to have control over how they stream the data in during read; if we attempted to buffer the whole frame we could easily hit OOMs (an attack vector, too). Obviously, sane clients don't send this much data in a single frame, but the protocol allows it.

A second option would be to allow the user to specify a max frame size in the frame reader constructor, and then just throw if the header indicates the payload length exceeds the max.

**Comment by davidfowl** [comment]
> The WebSocket protocol allows a single frame to contain up to ulong.MaxValue (!) bytes in the payload. My assumption was that we would want the consumer to have control over how they stream the data in during read; if we attempted to buffer the whole frame we could easily hit OOMs (an attack vector, too). Obviously, sane clients don't send this much data in a single frame, but the protocol allows it.

Why do we need to buffer? I'm missing something.

**Comment by mattnischan** [comment]
It's possible I'm missing something as well or misunderstanding you, so I'll run through what I'm thinking.

> why not do it before returning?

My assumption here is you're saying that we should do the unmasking of the payload data before we return the reader to the consumer. The problem is that the sequence is not guaranteed to be the full payload length, so that leaves us with a few options:

* Keep returning false until the sequence _is_ large enough to contain the payload, then unmask the whole thing and return it all. This may mean that we (the message reader) aren't buffering, but somebody upstream definitely is (potentially a lot of buffering).
* Unmask the part of the payload we do have immediately before returning. I'm not sure what the benefit to doing that would be though, since you'd still have to provide a reader to track the state of the remaining payload length and current index into the masking key.
* Don't attempt to consume anything beyond the header and just return a reader that does the unmasking for the consumer.

**Comment by davidfowl** [comment]
Can the payload reader be embedded in the `WebSocketFrameReader` to keep track of the current index and masking key?

Aside: IMessageWriter should take the TMessage is in not ref.

**Comment by davidfowl** [comment]
@mattnischan Are you going to send a PR?

**Comment by mattnischan** [comment]
@davidfowl I figured you'd want at least some tests first. How complete do you want it before putting in the PR?

**Comment by davidfowl** [comment]
Yes, you're right, Some tests would be great. I see some bugs around how SequencePositions are being created as well.

**Comment by mattnischan** [comment]
Any pointers there? This is my first foray into this API.

**Comment by davidfowl** [comment]
Easier to comment on a PR but here (and anywhere you create a SequencePosition using new):
https://github.com/davidfowl/BedrockFramework/compare/master...mattnischan:master#diff-ef31112a68bae6c4068a4dd401f842e1R60

Should be `input.GetPosition(bytesToRead)`

Either you get the current position from the SequenceReader or you get it from the ReadOnlySequence itself.

**Comment by mattnischan** [comment]
Good call. I'll just toss in the PR where I'm at now and I can add tests to it; at least it gives us a frame of reference.

**Comment by davidfowl** [comment]
I'm going to call this done for now. We can open other bugs as issues come up.
