### ISSUE TITLE
FSharp Interop with IMessageReader

### ISSUE THREAD

**Issue by auslavs** [davidfowl/BedrockFramework#48]
I have stumbled across an issue when trying to implement the IMessageReader interface in F#.
This is not so much an issue with the BedrockFramework as it is the FSharp compiler but I thought I might make it known here as well.

The FSharp compiler seems to struggle with the tupled arguments required for the TryParseMessage method.

I have added to an existing issue in the FSharp repository [here](https://github.com/dotnet/fsharp/issues/6379#issuecomment-571545894)

I have also created a minimal reproduction of the issue:
https://github.com/auslavs/errorFS2014

**Comment by jkotalik** [comment]
I don't think there is really anything we can do about it here. From what I can tell, the TMessage type is the tupled struct that it is failing to parse.

**Comment by davidfowl** [comment]
Yep, seems like a compiler, issue. Lets keep track of it though.

**Comment by auslavs** [comment]
Sorry I should have made it clear that my intent was just to log the issue so that F# people didn't scratch their head for longer than necessary.

I dug a little deeper and it appears as though the F# compiler has an isssue with "in" modifier on the first parameter. Removing the "in" modifier from the interface allows the FSharp implementation to compile and run.

```
public interface IMessageReader<TMessage>
    {
        bool TryParseMessage(in ReadOnlySequence<byte> input, ref SequencePosition consumed, ref SequencePosition examined, out TMessage message);
    }
```

Hopefully this will be fixed in the FSharp compiler in the near future.

**Comment by TIHan** [comment]
@davidfowl you can close this is you want. We resolved the issue in the compiler.

**Comment by jkotalik** [comment]
Thanks!
