### ISSUE TITLE
Web Api implementation

### ISSUE THREAD

**Issue by MithrilMan** [davidfowl/BedrockFramework#50]
I'd like to know if it's out of scope to have a WEB Api implementation on top of this library, that uses the same concept of mvc to discover Controllers and such so that we can have our custom web server to offer REST API for example.

This comes because of a need I have: I've a project composed of several class libraries (dotnet core 3.1) which are all part of a bigger solution.

It's basically a P2P network where I already use this library to offer listeners and to connect to other peers and it's modular, so I register a component and it will read configuration and do whatever it needs to do. What I want now is a component that exposes some Controllers (using swagger maybe) but I don't want to have a single endpoint that's offered by the core feature because I want to isolate each component and serve on a specific endpoint (that doesn't have to share anything between other components except the DI container that's common).

I tried to configure kestrel on top of bedrock but it's not working properly (may be because of some mistake I did or because Kestrel doesn't support this scenario)

Maybe it is possible to configure kestrel to have different endpoint (so listen to different endpoints) and have a different set of Controller exposed on each different endpoint, in any case I'd like to know if this library scope would cover such kind of scenarios.

Plan B is to wire a single kestrel and use a MiddleWare to expose controllers based on the endpoint, but I'd like more to be able to kick in kestrel servers at will so who wants to implements its own implementation doesn't have to deal with a pre-coocked API feature my software have.

Sorry for the textwall, I realize I'm going quite OT probably, in case just close the issue.

**Comment by davidfowl** [comment]
No there's no plan to build anything high level in this repository. The goal is to be a networking toolkit for building the networking stack that underlies tech like Kestrel and HttpClient though. Sounds like you're trying to build a specific application model on top of ASP.NET Core/Kestrel.

**Comment by MithrilMan** [comment]
yeah, closing
