### ISSUE TITLE
ProtocolReader.ReadAsync doesn't advance if read is successful

### ISSUE THREAD

**Issue by mgravell** [davidfowl/BedrockFramework#70]
The `AdvanceTo` is only invoked when read fails; most protocols will involve multiple messages, but the second call to `ReadAsync` reliably fails with:

> Unhandled exception. System.InvalidOperationException: Advance must be called before calling ReadAsync

Repro is [here](https://github.com/mgravell/Bedrock.Resp/tree/master/tests/SimpleClient)

**Comment by mgravell** [comment]
nm; I think I get it now - the `Advance` is manual *After* the `ReadAsync`. This is very intuitive, but... I guess it works?

**Comment by mgravell** [comment]
FYI, initial results - noting that **SE.Redis does a lot more and is optimized for different usage to this**:

``` txt
ExecuteBedrock: time for 1000 ops: 76ms
ExecuteStackExchagneRedis: time for 1000 ops: 92ms
```

**Comment by mgravell** [comment]
also: got it kinda sorta working in a BDN project, but now I'm seeing:

``` txt
 ---> System.InvalidOperationException: End position was not reached during enumeration.
   at System.ThrowHelper.ThrowInvalidOperationException_EndPositionNotReached()
   at System.Buffers.SequenceReader`1.IsNextSlow(ReadOnlySpan`1 next, Boolean advancePast)
   at System.Buffers.SequenceReader`1.TryReadTo(ReadOnlySequence`1& sequence, ReadOnlySpan`1 delimiter, Boolean advancePastDelimiter)
   at System.Buffers.SequenceReaderExtensions.TryReadTo[T](SequenceReader`1& sequenceReader, ReadOnlySpan`1& span, ReadOnlySpan`1 delimiter, Boolean advancePastDelimiter) in C:\Code\BedrockRespProtocol\src\BedrockRespProtocol\Lifted\SequenceReaderExtensions.cs:line 7
```

I'm assuming that is the bug @Drawaes was telling me about?

**Comment by Drawaes** [comment]
Yes the very same bug.... Might need to work around it ....let me have a look tonight

**Comment by mgravell** [comment]
On the API design: I think I'm in favor of the explicit `Advance`. This ties in well with allowing me to do a zero-copy parse that just deframes segments of the original buffer. Then we can call `Advance` once the deframed data has been processed. So: nothing to see here!

![nothing to see here](data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxMTEhUTExMWFhUXGRoaGBgYGBoXFxgXFRcYGBcXGBUYHiggGB0lGxcXITEhJSkrLi4uFx8zODMtNygtLisBCgoKDg0OGBAQFy0dHR0rLS0tLS0tLS0tLS0tLS0tLS0tLSstLS0tLSstLS0tLS0tLSstLS0tLS0tLS0tLS0tLf/AABEIAKkBKgMBIgACEQEDEQH/xAAcAAACAwEBAQEAAAAAAAAAAAAEBQIDBgcBAAj/xABHEAABAwIEAwYDBQUCDQUAAAABAAIRAyEEEjFBBVFhBhMicYGRBzKhFLHB0fAjM0JS4SSSFRY1U2Jyc3SCsrPC8RclNKKj/8QAGAEAAwEBAAAAAAAAAAAAAAAAAAECAwT/xAAfEQEBAQEAAwEBAAMAAAAAAAAAARECAxIhMUEiMmH/2gAMAwEAAhEDEQA/AJAouj0QrURSK566YPpIwec9UBTejqein+q/ixquaVSCply1lZWCAVIKhjlNr1eoxbC+XzXX5qdxYiL/AHJ7CxFfFSIvEXS2pjatJoz0i46ZmuaQZMCZi+ifsWGIXqGoY0OcGZXB2WXAtIDSDESRB6EckYQnpIher5fFMPl8vlJoSJ4F7CkAvoQaBC8K9K8KZPAV6Sq16g0iVAhSlewgIKL2yrMqlCR6Eq00M5MXhBVgs+ovmqVY0qMKQULWSvmlVFy9YVWpsFM0UlFitIVanFUXXIcdhXCo8d0bOdueZXYYWJ4jw15q1CHCC923+kVHX/GnFk/XgKvpOVHeWi2s6CffVed5ChUMabkyomyR4evKOo4hRVw1p3spOZHL0MoA4kgWU8NVkA5hJm03tzCJRYYtpjmradPSTYm9pNl7SpyASbncCB6Aq2m0Awb6e/JV7Jx8Q4jn6XjmrhhYBmx269IRNGnNrRqfu1RrGiJA031VSppU2m5wAEkwTta/PUqvH5gRLcoc9ggtBBki17bJ2GWMjyKExlEOcLSAQb9B4fruqQGruB2Ija0D1VYZM9Pf2TBrAP4bHrIsDEqt1MZQ7LBibWO15T0sLyvFc6f1uBoq7dZ/BVKWPIU2qBUmlVqcS/X6Ki4/r9frVSj9e369lWQmT4qLwpLwhAVSpNXxavg6EtNMtXgcvBUVZRowSovXjHr1xS0KnId7JXvEKjhTeWua0gEhz/kEbujZc1rdv8SJAbS3AMHykSfVLpXLo5oqDmrjze0eIdVFV1VxfzBgeQAsAnf+MteofE+OgsPYKcW6EQpMWMocQc5obmsP16o+li3MEg++iC1rGmCiGuXKncSrsrF7arzMnxG2sAQdoCYYftRWa4OL5lwmbi50A2WV8mXG08WzXRnIN/Dmkk8zPur2Vg9jXtNnCR5FWhy2kjD6wCrxNm+amhcc+AsmurcJXI3tMwdCdLjdM6eILQMrSSYBkA3JsAs3hMWCQPC2ASSZvF9t9k4bjDUdLt4GvoEqrk4diQ8BrQ7M75iRYOv8o0hV0WOBllNwgxnka6EgGLaonDta1gEgOkEyL9YcNlLGP/ZuiqBO0ERJicxIgG0rLWg7B4lpE3E6agk+f5c0cLGNVmxiQ3mH5QcxdIc4x8t4GhMkmeSZ08YST/F1nXrN+SrU4fUagAjfbqmWHed9Vm++dp4b72cI52NzpZOOG1cwF9P1MpxNhodF83DiIgQvJV1LRXKysQ7nafJC1Q0gyTa3rMeiPeIVVakf5jHLT6qiKa9EgnbnN7AQPJUV6dp3MdPp5Iys8AwBBJHI+gO/9EDVJ1n6REfr6o08UKbAviB6+vsvGOVTpNi4hQKrrYoN+YgDqQEufx/D5suefLT3Van1NVXUKEwvEGvJAcDFx1afxBt7c1a6qDPRHseVIuUSq3VEHicWWvpN2e4tPpTc772paMHNKi+oq+8sgX4m5HKPqlqsMRVVraqV0sRzRTKiPYeobtLWY3C1+8MNLHNmJu4QLQd4XE++BEHWF2TjvGaNCm7vXXcCAwQXOm3ynbzsuLObcRpP09Ez5jwIyhiTIB21VVSnCFFTxSUlY2PDq4IT2izO2J1ssVwjEgbrZ4F+WmXcrpdXImc3SZ1nuJAMeHzhI8Xi/EA02DgfMyPojeNYxrneGJ3SeqTlzRrcLnnP3XZuR1/snxDOw0jqy7d/CSRHobLQrnfw6qf2vFNnckDlJYfvK6JK6Y4r+sI6mcoO2nqlvFD4UxeUr4lcWuY0F78lmsqbTdnhsOjdtgZi0mJuYTzhD88N8IIO5A1J9/wSZmFa4WcS4AkjLGmt52Cvw4DcpzDrr4b/AFte3NTW0b91EANcYIJix5Dl+KXcccRRytdlLiwW6uvmdGmhgLx/E6bmgh0QIINjIkA+RAkIHjGOpGlZ4JkWnxaaxylRIYWq52UU3fwuJJNnEXixOn5+iYMxJpAOc4CTYtBDflB8JPzQTBSTucrWuaYBEOIM3i99iZ0UX1bhwfePCLywSconTrZBtq3iQiQ8OAElwuL6+R6J1gcc0RLgQAMxiNdBPTRc4wmJIaREAi/pcfVMcBxEhuUk+WxHUJpvLp+I4zh2MzF/pukdTtgS9optDWyJzGTlm56b81kcZiuRkA77jyQlFznOMEwJLdJ66m1vuCqVF5dsz5gD5FUY6oQGwQJmZsPlP4pB2W4rNFtKo4Z2W6lv8JMSBy1v6oftniRUoN7qq0PY8O1ymHAgEG1xe3RVrKc/THHuIN9BBgbW1zR5rOM7RNNZ9MluWJY4HNmB+b1kfQpbgOJuxTjRrVYDc+Yta0Cq24yXM6GdNlkeO4LJii6lUaCKgaGkklrmiQJI8bRAH9LpNcdDxXF2geEEmwAIgkm8xy2CRY/jVbSct4gCI/FTxON8YMh2WeoJi5EjSbxCX4qpTuXPkzYjTcEFuoO4QeQvqV3PdFRxjnN1S5sPIEx11siXVmTciPKVTWrsc+Qenmn9Hx7ghLvnLOR6oyjxOvSeQHZhvuDvKqwuSDmIFxE9QRP3IHHVgyZIPlafJA+NQzi7nET9OdkvxXHQ7EUqQHyuzOJ55Htgejrn8lkqvGqjgA3weRuR1QeCrFlZtQmQ0yef1808GR1IYvqkfFuKmjiWy6GFjcwI6uE+iV/4x0/5X/T80m47xHvntc2bNi+upP4pcy/0dZ/HR2umCL8kNiuJd1Vl7g2n3RJO8teNt5DvosTwrtFUo0iwAOv4Z/hB2/FLMbin1XFz3ZnHfpy6DoqnP1Bn2v4lSr1mvpmYblc6IBvIiRNr6pJTojKXdV8KRU2WBCqlE3v2QLxBnbf+iNe+yGrwkob2Uwj61dtNgmT7AXJT/tjxptKMPTM6ZyOmo+iC4PxZuGwtRtBrvtNQw55Hy0/5WRuTN1lsTRqG5Y72O6x+3r7+NvkgipVzukDy8kRW+Qg7Ax+SowVMjURbcQiawstPxG61vw+fGPrD+ZrT7sYfwXUoXHuyWKbTx1N7nBrXUKck6CxbPuuuNxVM3D2x/rD802PU+uf1CMrsxiBtcztZIi93igH5ibTeNSI6DbkpV+LFziW2ZqAbmPOLlLHYh4aXDNkuATbNsQL310HNSvDbDY5jBUZ3RJeHZHtEVAHDwtgkgN5xfqhaeJyE/K6GuFzI8Q1Bte5XjqzBTzZWZraX16jdeYKjUqNlpptEEOmQ4tJvOXbZLF6pp4svDaZLiJFm3LjIgkEwSBICtrUAxrAfmIJsQYEmGujRyk/BNpme9ptOsjNPS8WVT2tdMVaZIEwCZMcpCeF7GODyGjUB+cFpBPKYge5Q1MnNlBgEzcwJ5kqrD1TBANiL9QDI+qk9xOwPhLQNNrG3JF5E6F0XlzgWkExPIC0kGd1cahs8wM5JA5CeWwn7kpbh3s1DtJECb9Y0TJ2I/liCASANDyM7+XNZ2NeaZ2IF5HTfylFhrPCcpAcRq4R1Btbe/RKjiQ1viEktzNybFw8LTyEmbL1uJqGnkhszIk3hpu3W1x63RzE9/hgMXldNN2Q5TnJJggkABoFzCn3xJMfMQLOMOcSTEQLc7kJMcSAxjyS4kkZGwIyxlJg9Tc6q1nFcrgcry46BobmA2zOOhWlZcouxTmPa4EZo2AEbe9kJi3j9o4HM6o5r5IjIQ4uIFr6xy9lr8HhMPUbLqRBOodrf1MqriOFayMwaQdHkCSAAMp8o+qmVdZavxEui0AEnqZA16W+pVIrSbJhxPDgjw5fQAFLcJhH3cdG2PTqqidEPFlWHI7EcPN8rpAIEHXxCQhq2DcNFcR1cB1sUdCPog6751Vz8O4HQqqthXHmqxPsqp2mAqneSIbhHdV4/CP6+4Sw/YA6t0VtJ4OylWpPaQJJm9iPxU8P3Wr6sHkTf7kYfsgSvgRKPdjsNEZx9SqGnCk2rbSdYAQNUd5uq3vRrhRuab8wEe/K6pOu3qQgvwM59tEK8E6AppWZIkFojaRdAZHGxLf7w/NM5XtLEVG6ZvqiHY9+UA5ue6FdSd/M33H5qWU/zN/vBLD1acQTcknzurH3CAeHTq30cEfhKg7twluY6SQlh+wrC4ikGNzuAqBhZM7TMOHpIPmvPtlL/ADrPdI3w20g67yqYan6pt0+xDSAwgybyBt+dkA+scwBMXGpIaOcxoE3Y6CCQYBuYkXsNOqTcYZlqQNIlA187FkiI3JmTvtGwH4qmpWJVbQpev1Twasw9R0jU9JN/a6Ow9VwO9tv6FUYOk752/wABFwRIJPhj1GyvaSSSTJNz1JRg01wjgRJflmQQJNhcAjqfuTLhFAuEmLHlf3SRjjlm0AxtMm/mdFquzxHd38/ZZ+T5F+P7UaVCTlkNGQidoO58kkwNQtcCYiRYzGu4C1rWhwOUaggFIMeGURkEOfq4/hKji607+F2LqS4XMRe0TeSj+H0Wk28DSbOJl45xHQkJWa7byOZEazsDO2pUH4kNBAcTpECBO8ze2i0sZSizSOYD0F9tl9i67xULqbBYTJBgxtIS+li3SYAJIgSCYJ3A5/mjDXMRnyZjrqpquZ9advGHsdRmkMtRoJg6GOZsmfaLhwxOEeB81Md43rbxA/8ACg+C1JpgGo2qNiGgEDkRN/omXaPGihhahaDmqUi1sbF1j9CVjzf8m3f+rlbfIH1K0vAqI7mqDaYgBLezrGAObVaC19pIktI0IOoT/hvDcgJJnWIO3Vb9sOPoqlRBqwCYsT0LBqluKfmnqU24YT3Vd24aY9klZojxp838KquHIQ72O3Tt7J1CHfhybLViSvok7oCuCCn+Iw+UJDi9SmcDvpOPigfVCl7/ACXzg4628lA0SkaUv5lRdO6tw7o1EhU1B7IArDucQBNh0/HdEZTN49kFhiDrsj8LdBvamHdE2Q1RpGseydQNxKW40jQIECAE8vZfOY7p7Kt7AolrUGscw9PZeFpG49lUCAZF+m3krnOa4y0QCNEElSoNIBcbnyV+VnMfRM+z0FrpAN9SPJNYbyb7BLTWCmknG8I4vBAm0QNU/QuJJkEEg8xqniJWaa07qD2cvuCdfZJ2QtfDEIPQdE3/AKBH0HDcwOcTtayoFEqYplBrmguIABJJgDdaXhDHBsFZJmNfTfLYkDcc90dh+OV5iW3/ANEfeo651fNw+xfFqlPNTBHmNQs9WxW5MleYvFvL3AnWJ6wLfeUP9nc4o54kHXdqBxJmRaPyhFYWjmBJcBAEAgy6ToPS9199hTOpUECXNMT4jZztIzHoAABsnSleUMK9kOEtkGDpLTLT6ahCUMUwOLakxNiDomeGxoqVWMkvJIG5AaNb7ABA8a4IaVbK42fdkanpHqFFi+L9aTh2Np27txdaNyfLoodpsa6oG07+HW+tgQI6SmPY7sfUaQ6qTTbuDBd6xol1UMfUfldIzuiTyJj6KeOPu0/L5PmQnoUbQQraeMqUHBurHWB5J79nYxhc6IAkxewWPx3H84MU2wLwST7rWzWPHWVt+HUnnDvaLlzTljfp7JbhKdrpTwvtr3RESLEERIgiLdUZxXEmi4SbPAI9v0VPHOH5OvYRWICoGIaEtr4zNoZ9UOc50K0xmv4jiJB5pHTbLwDzV/F6hAaJ1n6Jdh3Q4FM4vr4eCeSHa0rQ0MUCPlBUMdTaAXwJNkHpASqayvBHNfESkaulQY2nmMl5MACwbuXE78oRtCoAgntheUygjipUlshLq5umPC4II5obi2GLXA7FAL3v6eq8dUvp+vZTKqqlBvO8PL6qFB3i91AvPVeU/mCCOMHizTYS0CZi/Uf0U/8ADdbkz+7/AFQrPkd5j8VFS0k+NsG2mRrEb+fkh3slWNKlCpiqY1Rq0JRDWq1rEACzBBSdgxyTJjFPu0aGI4owNqEDoo4dqv7QGK7h0H3KvCuSaT8GYaldGHKwST5dVRh8Q02Egjy+iEx4Mtkk+IIhUTVrE7ochfZ5MKTGkmBqUBquyXDiym+vlGZ/hYToG/xGBzI+iRiizE40se50FxaXfxEiYvykR0W/4gwUMM1v8lIe8SfrK512bH9qpE71AT7yUqrn+10vg/E61KjUZV8RYw90TMkAWa47xYyud0sRI11XQOO1y3DVTaS1x9xb6LlTK0AIxMpu3EG9/wBeSKwFJlQlpY2C0zDRIkWKzzcRurDxHKcoJHMjlyT+jIRtMG63dsTg2Bx8bGwDzyEx/wDW3osWMpcQdCbFaHgVfKzLyKCoelhi0zdEtrQExxWGN4FkoxFMggdR96rSAcWJzNbyE/3v/CFptMhMuJ0SarnHy9goMoaJauR415bBVWLqPdBcCBtyP5pnQpEkNG/6lX1MI58AEZWzlEaTr7wjU0t4bwY1SLwIJny2UuK8L7p0AyPKEUGVqR8JbHkqK5rPkuId1KBCt7JVFPdFvaRyVVKjeAJRqpF2BqGYGqMqszi5uieGNa1vh1/inX/wpVsLYls32+9Y9d/cb+Pnln3sgwVXWsNE0qYU1IGkaQh6eKcx+SQ5oN4Av5E7rTnrWffFlLWhfVGQQeaYuBkOygHUWF/TReFpcIMETPkeY5J6j0qzh+sc/wCqFqC511KO4UB3rZEiRZaY9ncMb5ze+vNJVuIsVzGoNrkTSqKmIhrVa1qrY5WhyRPQpEquVF70Bje0Z/tL/IfchcOUfj8M6s8vNnfgF9R4JUNw5v1/JDSVCjU5qvGYm7R1n6Ji3glWLuZ9UBxbhPdNFQvkyBEQNCfwQNirD1JctF2SwoqYkSJDQSsvgTc+X4radhTD3noPvRQf9u8TlonrAWL7JsDsXSB0BJ9mmyfdv8T4Gt6hJuw1PNi2n+Vrj9I/FKq5/K2/ah/9mrH/AET9VyaobLqnas/2WqOY/quVYjRNEDOcq2VLqdQKnKR6pmslM+E4mJCVIjCyHcjE35DdAdFwpzNBG4Ua+FbYkaL5telSpMIfIIECIMkA25gzr0PJVYHiQquc2AIuOZG8pICYzDAzCVtpkGCtFVpXleMwzTsg5cL8LhwGl2hNhNjG5/D3TDDUhC97kOdJ02HTZF0qQCBoPFUgEuxDJaQBdPqrA4JdX8O24HuYQJWXxFIgaLzBVBEDXdPa9IExFyhjwg6wjFXoEWHUaj6o3D4jMOR3CqezLZ1vNfMawkHPHURb80u+J0fHd5L+Ll4OSmIkS4jkbATsEiFTKbiYOmy2ONw9N4H7VgcN51CyPEaIZUc0EETYjQgiUczIrvrfr6niYfmaLcjfzumNOqDcIDhlHO/LBMjQXJ3P0Ca1+Hupx4SBtOt9LBHQ4rzBOHeNnTMJ8pErbfZ6X+a+v9Vg21S146GesgqypxSiSTNa5nRm6IXkPGORDCkwrOH8Z+oRNKs7n9U0YcMerW1EmOId+ivWYlyZYdByhUclrcSVPvykTqHwk4PQq0a7qtKnUIq2LmhxAyNMAkdVqf8AAeBxPfUxh2NNJ5pFwaGODsjHy1zdoqN+qRfBh84av/tf+xqq7U/E2ng61ehSwj31mOguljaZeWMOYkEuPhLdpsmR12E4XQfgaLn0abneIEloJJbUc3UjouXcB7CYjilDP3rKVPOfGQXFxbIIawRaTrK6p8LXuPC8MXfMWuJ2uajibeaq+FAA4XQ86h96r0ByvtD8KK+DouxFOszEU2iXQ0sc1ouXC5DgPMLRdgOw9V2HbXqPbSa8ZmyCXFp0J0gb+q3L8Wyrwt5o0stF2HqBoLhIbkcIIv8AehOzLXnhNN2Oczujh2S2m1zS2mGCJfmJcSI0A1QNc8+KfY7EUG06rSKtMuyGAQ4PfAYMvIm0zqQnnY74WVsOe9rYimHvblyNaSGk3jOSMxtsFqviw9w4ZUdTEvFTDFgO7hiaWUe6a4DG9/TpnFUHYatmGVr3MJFXK7929pIcYzdY2Rh+1zHPe1/AK5qU8IyHPrA5TNoHzOPICLoB3wRqFv8A82n3kTl7s5ffNMTvC244bVp8WwzquIfWBo1xTzhgLf3ZcPA0T/DcrRV8XTbi2Uwwms6i5wdMDu2vYCPPM4HTZGFr8ucf4HVwtZ+HrNAqM1gy0g3DmncFa/sj8K6nEMNTxBrtosgtaMhe4lr3S43AAV3xp/ypJEH7PS3n+Or+S6j8Jf8AJeH/AOP/AKjkKt+arw/ZDC0eH5XUMO+oygc1QU2nM9rD4wSJ1vKC7Gdn6D+FYeo/DUHPOHlz3sBcTBuTlTrgx/8AZ2f7sf8AkKt7JAf4LoRp9nH/ACITrlXZj4d1sbgqVZ9RmHpwXMkF7iw3LiPCGNmSBJsqON/D3EcOfSrd62tTfUZTzBpaWmq4NGZsmRfUHkuhdgMXm4VTp4uhloCgQaji3u3UMpnPeW+GZm1kP8SuFV+7pVmYp7qAxGGLqDmsLb12BrmPDc2pFiSgaHq/DWoI/tNMSQPlI15XueiSdpuyVXCGkA8Ve+fkbDSDn1DYvqATPQrqHaf5KX+8Yf8A6rUt7an9vwz/AHwf9CsjCZvDfDeplHeYhjXn+ENJExpJIn2SdnZmuMaMG8ta5zC9r7ua5o3ix2IhdR4vi6bK2FDmF1R9R7aRFg1wo1HOJvpka4b6pLxFx/wxgpbH7DE7zoaXLzKMDL8W7A1KFKrXdWY5tKm+oYa4OJY3NlF941+ijhvhxiKtEGrXp0S8AhuUvLXG7fES2TMWTH4vcZxNPusNh3NY2tTq96S0OOQANiXWb8xvqtPw3GGtQpjGUDQeHU4D3NLTUBHdmm5pNy6IBug3K+Idlq+FxNKhVLatTEnLSewENcW6gtN2QIJudCVqW/DWplviWB5ExkJHW8yRcXhHcR4XiKfFcC+piXV6JdWDGvawOpPNIk+JjRnBAOui1WPxVNuJoMLC6s+nWyGYDWNNI1Ab7k09tkB+eu1nB6+Hruo1KZJEGWy4OadHNtp+Sz9Si7dro6tIXUfjDUq/baWWmSe4vkJLgBUMGW+ZWAdRc/aq12kPY9tx1iEauA6dGjkBJ8Yu5pkgNG5y7eqS8aaM+djS1jgC0EzpaxT08NqSf2YPMxM+yXcYo1AwipTLYIyuDYbe0dEtPFfZmi8vLmDxAWJ0BJAPrBTvE4SpUcIZNRjgS7NLSB0GiV8BqvyEMbmvMRPS6dGvVtNEaWhoP/aiiKq/DDVdnMNnXUxHpeVE4Cjyqf3QrWue6ZokWm+YewA1VX2Mf5s//p+SQAAq1rlS1SVAS16ua9DMVgSJfTcBufUyr2vQTVe1BNt2N7bjAUns7g1S9+aRUDI8IEXBnRZ/i/EvtGJr4gsyd68ODc2bKBTYy7gBPyT6pYvkydD4B8SvsuHp0BhTUyAjMKobMkn5S081neyXxSfw9pw9Sh3tJpJGVwa9hcZcASIcJJ5LPs1WXx3zu80CR0vtR8XRWwrsJg8L3DHtLC5zhLWOEOaxjRAJBN53Tvs18SiOHtpVcH3ppsFKz2hjw0Q3M1wkWiYlcSZqth2d/dO8/wAEDGm7dfFgYvDVcI3CupvLqZFTvA4NNKoypplE/LCf9mvix9paG1cDnq0gHZmvblzXbna14GU3O51XEcX+8qf67vvK1Pw4/e1v9mP+ZFq/WY1HaTt/inY6hiRTZTFAODKWbPmFSA/vHgDUACALRN0//wDWCn+8PD3GqGloIqMiDBIzkZgJAOmy5t2j/eH9boOnp+uSE5FvaLjlXGYp+JrQHOgBrflYxvysB31JnckroHYLt87C4M0ThzVFLM5uV4a6HS6CCL3lcufqtJ2X0d/w/ikqz42WA+LrcRQfRp4AsGQttWaGtzAgQMiv4T8Qvs+Ep4X7MX5KQYX96GgmIPhymy5T2X1reY+9yfJoxsezPbn7Pg2YSthxXY1mT5gCWkXaWuEOFyNRZfdo+3T8YKVBtAUKIq0nPLnhzi2lUa8NDWiGiWi8nRY5QbqgOx9o/iFgWUppvp4l7alP9kCQfnALwS0wW/N6LF9qO3FXFVaDqdLuW4d/egueHOe/KWiwEBoBO952WSUkDHRh8UGnK6pgsz2SWubUbAcWlpIzgFsgkb2KQUu29V3EBjqtIRTpvp0qLX2DX3JNQtu4wJtFgswVS5AaPtj2nOPq0nmh3Qpse394HyXlp2Aj5VocN8Th3bWYjCd6W5SHNc27mGWuyvEAggGQdVzlSCA1nG+3uIxGJoVm020W4clzGZu8LnOblJe4AADKXCBz1T4/FVlnuwJdVaCGkVGwA6MwDnAFoOVs2OgXNl45AxsOFfEGq3F1sXXpB5qMZTZSY/K2mxji75yDmJLiSYCzvEuMGtWrVjLO8eXBubNlBAAE25JZW0Qj0Azdi28/qlnHnipSyC7pEbDzKrReGQYbC8O7iqAx+ZoBD3DRxtGVMe+81S/VfIJacR5+6j3x5/VUFQQH/9k=)

**Comment by rusuly** [comment]
Hi, sorry for interfering in the conversation. I think StackExchange.Redis could run faster if it targeted .NETStandard 2.1. At least my benchmarks show that SequenceReader(compiled in netstandard2.1) performed much better than BufferReader class(from SE)

**Comment by mgravell** [comment]
@Drawaes I worked around it by changing to the super-sophisticated:

``` c#
if (sequenceReader.TryReadTo(out ReadOnlySequence<byte> payloadPlusPrefix, (byte)'\r')
    && sequenceReader.TryRead(out var n) && n == '\n')
```

which correctly locates my CR/LF pairs without falling in a mound.

Allocations are higher than the competing code, note - I think this is probably TPL overheads:

|  Method |     Mean |    Error |   StdDev | Gen 0 | Gen 1 | Gen 2 | Allocated |
|-------- |---------:|---------:|---------:|------:|------:|------:|----------:|
| SERedis | 84.47 us | 1.214 us | 1.136 us |     - |     - |     - |     360 B |
| Bedrock | 77.38 us | 1.053 us | 0.985 us |     - |     - |     - |     704 B |

**Comment by mgravell** [comment]
initial allocations count based on 1000 operations:

Name	Total (Allocations)	Self (Allocations)	Total Size (Bytes)	Self Size (Bytes)
 - System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1	3009		601392	
 - Bedrock.Framework.Protocols.ProtocolReader.<DoAsyncRead>d__13`1	1001		136136	
 - BedrockRespProtocol.RespClientProtocol.<<ReadAsync>g__Awaited|7_0>d	1000		128000	
 - Bedrock.Framework.Protocols.ProtocolWriter.<WriteAsync>d__6`1	1001		112112	
 - BedrockRespProtocol.RespClientProtocol.<PingAsync>d__3	1000		112000

going to see what happens if I use `PooledAwait` on that...	will also see if I can get the .NET 5 bits working

**Comment by mgravell** [comment]
with `PooledAwait` on 2 of my methods, this becomes

Name	Total (Allocations)	Self (Allocations)	Total Size (Bytes)	Self Size (Bytes)
 - System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1	1011		217776	
 - System.Threading.QueueUserWorkItemCallbackDefaultContext`1	1003		32096	
 - Bedrock.Framework.Protocols.ProtocolReader.<DoAsyncRead>d__13`1	1001		136136	
 - Bedrock.Framework.Protocols.ProtocolWriter.<WriteAsync>d__6`1	1001		112112	
 - Resp.RedisSimpleString.RedisSimpleStringMemory	1001		40040	

The `RedisSimpleStringMemory` is my actual objects - fine with those

The AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1 are from Name `Bedrock.Framework.Protocols.ProtocolReader+<DoAsyncRead>d__13`1[System.__Canon]::MoveNext`

The QueueUserWorkItemCallbackDefaultContext are from `Bedrock.Framework.SocketReceiver+<>c::<.ctor>b__3_0	1002`

**Comment by mgravell** [comment]
most of the allocs *should* just evaporate if we can justify turning on the task amortizer bits; the ones that remain are the `QueueUserWorkItemCallbackDefaultContext` from `SocketAwaitable.Complete` - I can't see how I could bypass those since `PipeScheduler.ThreadPool` is hard-coded in `SocketConnection`.

**Comment by JanEggers** [comment]
@mgravell found the same and created https://github.com/JanEggers/BedrockTransports/commit/4ed38b6e6692621ea6909411dba512725071a919

should i create a pr or are the more buildin solutions?

**Comment by davidfowl** [comment]
The fix is this https://github.com/davidfowl/BedrockFramework/issues/19

**Comment by mgravell** [comment]
@JanEggers  see https://github.com/dotnet/runtime/issues/13633

**Comment by mgravell** [comment]
@JanEggers that custom scheduler looks pretty hairy re concurrency; I wonder if it would be better to simply test the `state` arg to see if *that* is a `IThreadPoolWorkItem` - and if so, `UnsafeQueueUserWorkItem` it - otherwise push it to the thread-pool; or wait for David's voodoo

**Comment by JanEggers** [comment]
I guess voodoo is the best option

**Comment by davidfowl** [comment]
Closing this in favor of #19, which should solve most allocations except the state machine. That one will require more work see https://github.com/davidfowl/BedrockFramework/issues/20

**Comment by mgravell** [comment]
@davidfowl  the state machine evaporates if we https://github.com/dotnet/runtime/issues/13633
