### ISSUE TITLE
No CancellationTokens passed into methods of Protocol classes 

### ISSUE THREAD

**Issue by Ninds** [davidfowl/BedrockFramework#71]
ReadRequestAsync, WriteResponseAsync & SendAsync methods in the protocol classes do not accept CancellationTokens. Is that by design? If so, what is the rationale?

**Comment by davidfowl** [comment]
Oversight, those APIs aren’t final anyways. Feel free to send a pull request

**Comment by Ninds** [comment]
Will do this evening.

**Comment by Ninds** [comment]
#74
