### ISSUE TITLE
Is ClientBuilder.Build supposed to be Threadsafe ?

### ISSUE THREAD

**Issue by Ninds** [davidfowl/BedrockFramework#72]
@drawaes As per your suggestion I replaced  Pipelines.Sockets.Unofficial with Bedrock for client side connections. Also I cached the instance of ClientBuilder for re-use. However it appears that the Build method is not threadsafe. 
If 
`ClientBuilder clientBuilder = new ClientBuilder(new ServiceCollection().BuildServiceProvider()).UseSockets();`

and I execute :

`await clientBuilder.Build().ConnectAsync(new IPEndPoint(IPAddress.Loopback, Port), default);`

from 20 threads, I have the following often :

`    System.ArgumentException : Destination array was not long enough. Check the destination index, length, and the array's lower bounds. (Parameter 'destinationArray')
  Stack Trace: 
    Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
    List'1.CopyTo(T[] array, Int32 arrayIndex)
    EnumerableHelpers.ToArray[T](IEnumerable'1 source, Int32& length)
    Buffer'1.ctor(IEnumerable'1 source)
    ReverseIterator'1.MoveNext()
    ConnectionBuilder.Build()
    ClientBuilder.Build() line 55
`

If on the other hand I use :

`clientBuilder.Build().ConnectAsync(new IPEndPoint(IPAddress.Loopback, Port), default).Result;`
no exception.
Am I missing something ?

**Comment by Drawaes** [comment]
I wouldn't cache the builder but the actual client.  So then you just call ConnectAsync each time on the one cached client (not client builder). That way you can take advantage of things like connection pooling etc

**Comment by davidfowl** [comment]
That’s right. You build the client once (which itself is a factory) and that then can be used to create more connections.

**Comment by Ninds** [comment]
Thanks Guys! 
It's what I figured out before going to lunch! 
Bloody obvious with hindsight when you see that there is an effort to reproduce on the client side the pattern seen on the server side.
